language: ruby
rvm:
  - 2.5
jobs:
  include:
    - stage: test
      script: rake test
    - stage: build docker image
      if: branch IN (master, develop) AND type != pull_request
      services:
      - docker
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t securecodebox/nikto:oss .
      - docker images
      - docker push securecodebox/nikto:oss